adjust plan step

diff --git a/.github/workflows/tofu-plan.yml b/.github/workflows/tofu-plan.yml
--- a/.github/workflows/tofu-plan.yml
+++ b/.github/workflows/tofu-plan.yml
@@ -63,8 +63,18 @@ jobs:
 
       - name: OpenTofu Plan
         id: plan
-        run: tofu plan -no-color -out=${{ inputs.plan_name }}.json
         continue-on-error: true
+        run: |
+          set +e
+          tofu plan -no-color -out=${{ inputs.plan_name }}.json > plan.log 2>&1
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
+
+      - name: Show Plan
+        run: tofu show ${{ inputs.plan_name }}.json
+
+      - name: Show Plan Log
+        if: steps.plan.outputs.exit_code != '0'
+        run: cat plan.log
 
       - name: Upload Plan
         uses: actions/upload-artifact@v4
@@ -75,7 +85,7 @@ jobs:
       - uses: actions/github-script@v6
         if: github.event_name == 'pull_request'
         env:
-          PLAN: "tofu\n${{ steps.plan.outputs.stdout }}"
+          PLAN: "tofu\n$(cat ${{ inputs.plan_name }}.json)"
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
@@ -97,3 +107,9 @@ jobs:
               repo: context.repo.repo,
               body: output
             })
+
+      - name: Fail job if plan failed
+        if: steps.plan.outputs.exit_code != '0'
+        run: |
+          echo "OpenTofu plan failed. Failing job."
+          exit 1
